/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: bigint;
    inStock: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: bigint;
    weightOptions: Array<WeightOption>;
}
export interface WeightOption {
    weight: bigint;
    price: bigint;
}
export interface CartItem {
    weight: bigint;
    productId: bigint;
    quantity: bigint;
}
export interface Review {
    content: string;
    authorEmail: string;
    productId: bigint;
    author: string;
    rating: bigint;
}
export interface WishlistItem {
    weight: bigint;
    productId: bigint;
}
export enum Category {
    nuts = "nuts",
    dryFruits = "dryFruits",
    seeds = "seeds"
}
export interface backendInterface {
    addToCart(productId: bigint, weight: bigint, quantity: bigint): Promise<void>;
    addToWishlist(productId: bigint, weight: bigint): Promise<void>;
    clearCart(): Promise<void>;
    filterProductsByCategory(category: Category): Promise<Array<Product>>;
    filterProductsByPriceRange(minPrice: bigint, maxPrice: bigint): Promise<Array<Product>>;
    filterProductsByWeight(weight: bigint): Promise<Array<Product>>;
    getCart(): Promise<Array<CartItem>>;
    getCategories(): Promise<Array<Category>>;
    getOverallReviews(): Promise<Array<Review>>;
    getProductDetails(productId: bigint): Promise<Product>;
    getProducts(): Promise<Array<Product>>;
    getReviews(productId: bigint): Promise<Array<Review>>;
    getWishlist(): Promise<Array<WishlistItem>>;
    removeFromWishlist(productId: bigint, weight: bigint): Promise<void>;
    searchProducts(searchText: string): Promise<Array<Product>>;
}
import type { Category as _Category, Product as _Product, WeightOption as _WeightOption } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToCart(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1, arg2);
            return result;
        }
    }
    async addToWishlist(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0, arg1);
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async filterProductsByCategory(arg0: Category): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProductsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProductsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterProductsByPriceRange(arg0: bigint, arg1: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProductsByPriceRange(arg0, arg1);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProductsByPriceRange(arg0, arg1);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterProductsByWeight(arg0: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProductsByWeight(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProductsByWeight(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverallReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverallReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverallReviews();
            return result;
        }
    }
    async getProductDetails(arg0: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductDetails(arg0);
                return from_candid_Product_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductDetails(arg0);
            return from_candid_Product_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async getWishlist(): Promise<Array<WishlistItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async removeFromWishlist(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0, arg1);
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inStock: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: _Category;
    price: bigint;
    weightOptions: Array<_WeightOption>;
}): {
    id: bigint;
    inStock: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: bigint;
    weightOptions: Array<WeightOption>;
} {
    return {
        id: value.id,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category),
        price: value.price,
        weightOptions: value.weightOptions
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nuts: null;
} | {
    dryFruits: null;
} | {
    seeds: null;
}): Category {
    return "nuts" in value ? Category.nuts : "dryFruits" in value ? Category.dryFruits : "seeds" in value ? Category.seeds : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    nuts: null;
} | {
    dryFruits: null;
} | {
    seeds: null;
} {
    return value == Category.nuts ? {
        nuts: null
    } : value == Category.dryFruits ? {
        dryFruits: null
    } : value == Category.seeds ? {
        seeds: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
