/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'nuts' : IDL.Null,
  'dryFruits' : IDL.Null,
  'seeds' : IDL.Null,
});
export const WeightOption = IDL.Record({
  'weight' : IDL.Nat,
  'price' : IDL.Int,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Int,
  'weightOptions' : IDL.Vec(WeightOption),
});
export const CartItem = IDL.Record({
  'weight' : IDL.Nat,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Review = IDL.Record({
  'content' : IDL.Text,
  'authorEmail' : IDL.Text,
  'productId' : IDL.Nat,
  'author' : IDL.Text,
  'rating' : IDL.Int,
});
export const WishlistItem = IDL.Record({
  'weight' : IDL.Nat,
  'productId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'filterProductsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'filterProductsByPriceRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'filterProductsByWeight' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getOverallReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getProductDetails' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
  'removeFromWishlist' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'nuts' : IDL.Null,
    'dryFruits' : IDL.Null,
    'seeds' : IDL.Null,
  });
  const WeightOption = IDL.Record({ 'weight' : IDL.Nat, 'price' : IDL.Int });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Int,
    'weightOptions' : IDL.Vec(WeightOption),
  });
  const CartItem = IDL.Record({
    'weight' : IDL.Nat,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const Review = IDL.Record({
    'content' : IDL.Text,
    'authorEmail' : IDL.Text,
    'productId' : IDL.Nat,
    'author' : IDL.Text,
    'rating' : IDL.Int,
  });
  const WishlistItem = IDL.Record({
    'weight' : IDL.Nat,
    'productId' : IDL.Nat,
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'filterProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'filterProductsByPriceRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'filterProductsByWeight' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getOverallReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getProductDetails' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
    'removeFromWishlist' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };