/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'weight' : bigint,
  'productId' : bigint,
  'quantity' : bigint,
}
export type Category = { 'nuts' : null } |
  { 'dryFruits' : null } |
  { 'seeds' : null };
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
  'weightOptions' : Array<WeightOption>,
}
export interface Review {
  'content' : string,
  'authorEmail' : string,
  'productId' : bigint,
  'author' : string,
  'rating' : bigint,
}
export interface WeightOption { 'weight' : bigint, 'price' : bigint }
export interface WishlistItem { 'weight' : bigint, 'productId' : bigint }
export interface _SERVICE {
  'addToCart' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'addToWishlist' : ActorMethod<[bigint, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'filterProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'filterProductsByPriceRange' : ActorMethod<[bigint, bigint], Array<Product>>,
  'filterProductsByWeight' : ActorMethod<[bigint], Array<Product>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getOverallReviews' : ActorMethod<[], Array<Review>>,
  'getProductDetails' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'getWishlist' : ActorMethod<[], Array<WishlistItem>>,
  'removeFromWishlist' : ActorMethod<[bigint, bigint], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];